
[core]
name: EkHarvesterSolarOff
copyFrom: ROOT:_EKE_/Buildings/Fabricators/harvester_solar.ini
generation_delay: 0
generation_credits: 0
generation_resources: uranium=0

#---------------------added
[hiddenAction_noJacas]
requireConditional:  if not self.globalTeamTags(includes='EKE_noHack')
autoTriggerOnEvent: created
addResources: 1500
deleteSelf: true
showMessageToPlayer: Unauthorized!
showMessageToPlayer_ru: Китай Партия не одобряет такой деятельности!
showMessageToPlayer_zh: 未授权!
#---------------------
[graphics]
total_frames: 1

image:        harvester_solar.png
image_wreak:  NONE
image_turret: NONE

#scaleImagesTo: 20
#scaleTurretImagesTo: 9

#AUTO
image_shadow: AUTO
shadowOffsetX:1.5
shadowOffsetY:1.5

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false

maxAttackRange: 0

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01

maxTurnSpeed: 0
turnAcceleration: 0.1

[ai]


buildPriority: 0.3
noneInBaseExtraPriority: 0.1
recommendedInEachBasePriorityIfUnmet: 0.4
noneGlobalExtraPriority: 0.4
ai_upgradePriority: 0.9

recommendedInEachBaseNum: 0
maxEachBase: 0
#maxGlobal: 40