<<<<<<< HEAD

[core]
copyFrom: ROOT:effects.template, ROOT:statusEffect.template
name: grandSlamBomber
class: CustomUnitMetadata
price: 85000, uranium=4250
maxHp: 5500
mass: 60000000

techLevel: 2
buildSpeed: 120s
availableInDemo: true

displayText: Perdoon
displayDescription: - Very fast but turns slowly\n- Heavily armored\n-Carries 1 50-ton bomb\n- Also has a quantum torpedo to attack subs\n- Takes a long time to recharge\n- Can self-repair\n- defenseless vs air\n- Deals double-damage to buildings\n- Can only build 5 at a time 
displayText_ru: Perdoon
displayDescription_ru: Так называемый носитель \n- Держит в себе термоядерную какашку, наносящую конский урон по любым целям \n- Особенно хорошо уничтожается вражеское бетонирование на поле боли \n- Существенный самоотсос и невероятная динамика для своих размеров \n- Только пять штук на одно рыло (чтобы не вызвать у врага ПТСР)
radius: 38
displayRadius: 32
isBio: false
#softCollisionOnAll: 3
softCollisionOnAll:24
fogOfWarSightRange: 17

selfRegenRate: 1

energyMax: 1
energyRegen: 0.00015
energyNeedsToRechargeToFull: true

builtFrom_1_name: airFactory
builtFrom_1_pos: 11

tags: grand

[hiddenAction_refund]
requireConditional:  if numberOfUnitsInTeam(greaterThan=5, withTag='grand', incompleteBuildings=true)
autoTriggerOnEvent: created
addResources: 850000, uranium=2500
deleteSelf: true
showMessageToPlayer: You have built the maximum amount of Grand Slam Bombers you can have at the same time.
showMessageToPlayer_ru: Что?! Тебе и пяти хватит! Остановись!

[graphics]
total_frames: 1

image:        base.png
image_wreak:  base_dead.png
image_turret: NONE

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1

movementEffect: CUSTOM:trailGrand
movementEffectRate: 1
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: true

turretSize: 20
turretTurnSpeed: 1.5

maxAttackRange: 50
shootDelay: 30

attackMovement: bomber



[turret_1]
#bomber
invisible: true
x: 0
y: 0
idleDir:0
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

projectile: 1
size: 1.1
turnSpeed: 20

energyUsage: 1





[turret_2]
#anti-sub
invisible: true
x: 0
y: 0
idleDir:0
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: true

projectile: 2
size: 1.1
turnSpeed: 20

energyUsage: 1


[projectile_1]
#bomb
life: 250
speed: 0.01
targetSpeed: 3
drawSize: 3
color: #000000
trailEffect: false
largeHitEffect: true
tags:ifc
targetGround: true

areaDamage: 4000
areaRadius: 250


#for laser defence
deflectionPower: 35
buildingDamageMultiplier: 2.0
explodeEffect: CUSTOM|fart, CUSTOM|radialExplosionWater, CUSTOM|bigshockwave


lightColor: #ffe92b
lightSize: 0.4


[effect_fart]
alsoPlaySound:fart.ogg:100.0
priority: critical

[projectile_2]
#bomb anti-sub

directDamage: 0

life: 250
speed: 0.3
targetSpeed: 3
drawSize: 1
color: #000000
trailEffect: false
largeHitEffect: true

targetGround: false

#for laser defence
deflectionPower: 35
explodeEffect: CUSTOM|fart

areaDamage: 7000
areaRadius: 250

[movement]
movementType: AIR
moveSpeed: 1.9
moveAccelerationSpeed: 0.02
moveDecelerationSpeed: 0.0085

targetHeight: 50

landOnGround: onlyIdle


#note: joinsGroupFormations=false could case slowdowns for groups of non-flying units
joinsGroupFormations: false

maxTurnSpeed: 1
turnAcceleration: 0.0225

moveSlidingMode :false
moveIgnoringBody:false
moveSlidingDir:  25

slowDeathFall: true





=======

[core]
copyFrom: ROOT:effects.template, ROOT:statusEffect.template
name: grandSlamBomber
class: CustomUnitMetadata
price: 85000, uranium=4250
maxHp: 5500
mass: 60000000

techLevel: 2
buildSpeed: 120s
availableInDemo: true

displayText: Perdoon
displayDescription: - Very fast but turns slowly\n- Heavily armored\n-Carries 1 50-ton bomb\n- Also has a quantum torpedo to attack subs\n- Takes a long time to recharge\n- Can self-repair\n- defenseless vs air\n- Deals double-damage to buildings\n- Can only build 5 at a time 
displayText_ru: Perdoon
displayDescription_ru: Так называемый носитель \n- Держит в себе термоядерную какашку, наносящую конский урон по любым целям \n- Особенно хорошо уничтожается вражеское бетонирование на поле боли \n- Существенный самоотсос и невероятная динамика для своих размеров \n- Только пять штук на одно рыло (чтобы не вызвать у врага ПТСР)
radius: 38
displayRadius: 32
isBio: false
#softCollisionOnAll: 3
softCollisionOnAll:24
fogOfWarSightRange: 17

selfRegenRate: 1

energyMax: 1
energyRegen: 0.00015
energyNeedsToRechargeToFull: true

builtFrom_1_name: airFactory
builtFrom_1_pos: 11

tags: grand

[hiddenAction_refund]
requireConditional:  if numberOfUnitsInTeam(greaterThan=5, withTag='grand', incompleteBuildings=true)
autoTriggerOnEvent: created
addResources: 850000, uranium=2500
deleteSelf: true
showMessageToPlayer: You have built the maximum amount of Grand Slam Bombers you can have at the same time.
showMessageToPlayer_ru: Что?! Тебе и пяти хватит! Остановись!

[graphics]
total_frames: 1

image:        base.png
image_wreak:  base_dead.png
image_turret: NONE

image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1

movementEffect: CUSTOM:trailGrand
movementEffectRate: 1
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: true

turretSize: 20
turretTurnSpeed: 1.5

maxAttackRange: 50
shootDelay: 30

attackMovement: bomber



[turret_1]
#bomber
invisible: true
x: 0
y: 0
idleDir:0
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

projectile: 1
size: 1.1
turnSpeed: 20

energyUsage: 1





[turret_2]
#anti-sub
invisible: true
x: 0
y: 0
idleDir:0
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: true

projectile: 2
size: 1.1
turnSpeed: 20

energyUsage: 1


[projectile_1]
#bomb
life: 250
speed: 0.01
targetSpeed: 3
drawSize: 3
color: #000000
trailEffect: false
largeHitEffect: true
tags:ifc
targetGround: true

areaDamage: 4000
areaRadius: 250


#for laser defence
deflectionPower: 35
buildingDamageMultiplier: 2.0
explodeEffect: CUSTOM|fart, CUSTOM|radialExplosionWater, CUSTOM|bigshockwave


lightColor: #ffe92b
lightSize: 0.4


[effect_fart]
alsoPlaySound:fart.ogg:100.0
priority: critical

[projectile_2]
#bomb anti-sub

directDamage: 0

life: 250
speed: 0.3
targetSpeed: 3
drawSize: 1
color: #000000
trailEffect: false
largeHitEffect: true

targetGround: false

#for laser defence
deflectionPower: 35
explodeEffect: CUSTOM|fart

areaDamage: 7000
areaRadius: 250

[movement]
movementType: AIR
moveSpeed: 1.9
moveAccelerationSpeed: 0.02
moveDecelerationSpeed: 0.0085

targetHeight: 50

landOnGround: onlyIdle


#note: joinsGroupFormations=false could case slowdowns for groups of non-flying units
joinsGroupFormations: false

maxTurnSpeed: 1
turnAcceleration: 0.0225

moveSlidingMode :false
moveIgnoringBody:false
moveSlidingDir:  25

slowDeathFall: true





>>>>>>> upstream/REfI
