<<<<<<< HEAD

[core]
name: temp_C
showInEditor: false
mass: 99999999
copyFrom: basilisk_M.ini

#------------------------------------
builtFrom_1_name: NONE 
#------------------------------------
[attack]
isMelee: true
#maxAttackRange: 110

[movement]
moveSpeed: 1
maxTurnSpeed: 0
reverseSpeedPercentage: 0
[ai]
=======

[core]
name: temp_C
showInEditor: false
mass: 99999999
copyFrom: basilisk_M.ini

#------------------------------------
builtFrom_1_name: NONE 
#------------------------------------
[attack]
isMelee: true
#maxAttackRange: 110

[movement]
moveSpeed: 1
maxTurnSpeed: 0
reverseSpeedPercentage: 0
[ai]
>>>>>>> upstream/REfI
upgradedFrom: basilisk