[core]
name:EkHog
displayText:Hog
displayDescription:-Super heavy tank destroyer\n-Self propelled gun\n-Slow speed and reload time\n-Effective against a single target
displayText_ru: Свинота
displayDescription_ru: Кусок жира в стиле терпил \n- Недостаточно крепкий для Дудкера, но и не имеющий кучу рейнджа с мощью для бытия Вечной \n- ДОТ на гуслях, разваливающий кабины другим юнитам альфовым барабаном на три снаряда \n- Невероятно эффективен против экспы\n- От братьев по терпению далеко не уходил, посему против кислого абсолютный ноль

price:25000,uranium=250

maxHp:5000
armour:5
mass:24000
techLevel:1

buildSpeed:80s
experimental:true

radius:38
displayRadius:38

isBio:false
transportSlotsNeeded:5

fogOfWarSightRange:24
numBitsOnDeath:20
explodeTypeOnDeath:largeUnit
tags:Experimental

energyMax: 3
energyRegen: 0.0017
energyNeedsToRechargeToFull: false

[graphics]
imageScale: 1.15
total_frames:3
image:HogBase.png
image_wreak:hog_dead.png
image_turret:NONE
image_shadow:AUTO
shadowOffsetX:3
shadowOffsetY:3
animation_moving_start:0
animation_moving_end:2
animation_moving_speed:3.5
dustEffect:true



[attack]
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
turretSize:60
turretTurnSpeed:1.2
maxAttackRange:335
shootDelay: 180
aimOffsetSpread:0
isFixedFiring:true



[turret_1]
x:-5
y:43
image: HobBar9.png
idleDir:0
idleDirReversing:0
turnSpeed:0.01
projectile:1
shoot_sound:typhoonshoot2.ogg, typhoonshoot3.ogg, typhoonshoot1.ogg
shoot_sound_vol:3
shoot_flame:large
shoot_light:#FFEEEEEE
canShoot:true
recoilOffset:-4
recoilOutTime:3
recoilReturnTime:24
canAttackMaxAngle:0.0000000001
energyUsage: 1



[projectile_1]
directDamage:500
areaDamage: 250
areaRadius: 75
life:200
speed:16
frame:8

color:#bebe50
drawSize:1.2
largeHitEffect:true
targetGround:false

trailEffect:true
lightColor:#ffe92b
lightSize:0.6
lightCastOnGround:true
deflectionPower:10
tags:EKAmmo

turnSpeed:0

mutatorI_ifUnitWithTags: exp, apoc, konig, orion, 
mutatorI_directDamageMultiplier: 1.5


#explodeEffect:CUSTOM:1
#[effect_1]
#life:1
#alsoPlaySound:typhoonhit1.ogg:0.3, typhoonhit2.ogg:0.3, typhoonhit3.ogg:0.3, typhoonhit4.ogg:0.3


[movement]
movementType:LAND
moveSpeed:0.43
moveAccelerationSpeed:0.011
moveDecelerationSpeed:0.02
maxTurnSpeed:0.7
moveSlidingMode:false
moveIgnoringBody:false
reverseSpeedPercentage:0.95
