<<<<<<< HEAD

[core]
name: IsniperLong
displayText: Sniper
displayDescription: - Elite infantry with Anti-Tank Rifle\n -Can switch between recon and sniper mode \n -Can attack land only\n -Long range
displayText_ru: Стрим-снайпер
displayDescription_ru: - Элитная хуёта с дубинкой \n- Атакует только чернозём \n- Достаёт до дальних территорий \n- Урон по постройкам около нулевой
displayText_zh: 狙击手 [狙击模式]
displayDescription_zh:-装备反坦克步枪的精英步兵\n-必须处于狙击手模式才能使用远距离/大伤害\n-攻击地面和空中\n-远程\n-对建筑物的伤害很低
class: CustomUnitMetadata
price: 1000
maxHp: 60
mass: 200
showInEditor: false
techLevel: 2
experimental: false
buildSpeed: 0.0007
#availableInDemo: true

radius: 6
displayRadius: 12
isBio: true
isBug: false

transportSlotsNeeded: 100
isUnrepairableUnit: true

numBitsOnDeath: 5
selfRegenRate:0.08
softCollisionOnAll: 12

fogOfWarSightRange: 28

tags: infantry

[hiddenAction_buff]
text: assault mech buff
description: normally unreadable...
autoTrigger: if numberOfUnitsInTeam(withTag="cyborg", withinRange=250, greaterThan=0)
convertTo: IsniperLongBuff
spawnEffects: CUSTOM:powerFlash

[action_convertbk]
convertTo: Isniper
text: Put away sniper
text_ru: Бегом!!!
description: Switch to recon mode
description_ru: Возвращает Бориса из отаку режима в БЕГОМ!!!
buildSpeed: 1s
whenBuilding_cannotMove: true
displayType: upgrade
[hiddenAction_converTo_A]
#No tricks! force to convertTo hmgHelicopter bruv
autoTrigger: if self.hasParent(withTag='Helicopter')
convertTo: IsniperHelicopter
[graphics]
imageScale: 0.9
total_frames: 5

image:        isniper_sniper.png
image_wreak:  isniper_dead.png
image_turret: sniper.png
#scaleImagesTo: 20
#scaleTurretImagesTo: 9

#AUTO
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1


animation_moving_start: 0
animation_moving_end: 2
animation_moving_speed: 11
#animation_moving_pingPong: true

animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 120
animation_idle_scale_start:1
animation_idle_scale_end:1.03
animation_idle_pingPong: true

animation_attack_start: 2
animation_attack_end: 4
animation_attack_speed: 3


lock_body_rotation_with_main_turret: true


[attack]

canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

isFixedFiring: true

turretSize: 20
turretTurnSpeed: 3

maxAttackRange: 360
shootDelay: 250

[turret_1]
x: 0
y: 0
canShoot: false
invisible: true

[turret_2]
x: 3
y: 8
attachedTo: 1
slave: true
shoot_sound:cannon_firing
shoot_sound_vol:0.2
recoilOffset: -4


[projectile_1]
directDamage: 150
life: 50
instant: false
trailEffect: true
buildingDamageMultiplier: 0.05
speed: 30
trailEffectRate: 0.2
#deflectionPower: 0.5

[movement]
movementType: LAND
moveSpeed: 0.23
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.9


maxTurnSpeed: 1.0
turnAcceleration: 0.1

moveSlidingMode :true
moveIgnoringBody:false
moveSlidingDir:  181



reverseSpeedPercentage:0


[ai]
upgradedFrom: Isniper


[effect_powerFlash]
priority:low

frameIndex: 0
stripIndex: shockwave

life: 35
fadeOut: true
attachedToUnit: true
color: #FFFFFF
teamColorRatio: 0.8

hSpeed: 0.1
dirSpeed: 2

fadeInTime: 3
scaleFrom: 0.6
scaleTo: 1
alpha: 1
drawUnderUnits:true
liveAfterAttachedDies: true

[attachment_buff]
x:0
y:0

onCreateSpawnUnitOf: powerUp

canBeAttackedAndDamaged: false
keepAliveWhenParentDies: false

setDrawLayerOnBottom: true
rotateWithParent: false
=======

[core]
name: IsniperLong
displayText: Sniper
displayDescription: - Elite infantry with Anti-Tank Rifle\n -Can switch between recon and sniper mode \n -Can attack land only\n -Long range
displayText_ru: Стрим-снайпер
displayDescription_ru: - Элитная хуёта с дубинкой \n- Атакует только чернозём \n- Достаёт до дальних территорий \n- Урон по постройкам около нулевой
displayText_zh: 狙击手 [狙击模式]
displayDescription_zh:-装备反坦克步枪的精英步兵\n-必须处于狙击手模式才能使用远距离/大伤害\n-攻击地面和空中\n-远程\n-对建筑物的伤害很低
class: CustomUnitMetadata
price: 1000
maxHp: 60
mass: 200
showInEditor: false
techLevel: 2
experimental: false
buildSpeed: 0.0007
#availableInDemo: true

radius: 6
displayRadius: 12
isBio: true
isBug: false

transportSlotsNeeded: 100
isUnrepairableUnit: true

numBitsOnDeath: 5
selfRegenRate:0.08
softCollisionOnAll: 12

fogOfWarSightRange: 28

tags: infantry

[hiddenAction_buff]
text: assault mech buff
description: normally unreadable...
autoTrigger: if numberOfUnitsInTeam(withTag="cyborg", withinRange=250, greaterThan=0)
convertTo: IsniperLongBuff
spawnEffects: CUSTOM:powerFlash

[action_convertbk]
convertTo: Isniper
text: Put away sniper
text_ru: Бегом!!!
description: Switch to recon mode
description_ru: Возвращает Бориса из отаку режима в БЕГОМ!!!
buildSpeed: 1s
whenBuilding_cannotMove: true
displayType: upgrade
[hiddenAction_converTo_A]
#No tricks! force to convertTo hmgHelicopter bruv
autoTrigger: if self.hasParent(withTag='Helicopter')
convertTo: IsniperHelicopter
[graphics]
imageScale: 0.9
total_frames: 5

image:        isniper_sniper.png
image_wreak:  isniper_dead.png
image_turret: sniper.png
#scaleImagesTo: 20
#scaleTurretImagesTo: 9

#AUTO
image_shadow: AUTO
shadowOffsetX:1
shadowOffsetY:1


animation_moving_start: 0
animation_moving_end: 2
animation_moving_speed: 11
#animation_moving_pingPong: true

animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 120
animation_idle_scale_start:1
animation_idle_scale_end:1.03
animation_idle_pingPong: true

animation_attack_start: 2
animation_attack_end: 4
animation_attack_speed: 3


lock_body_rotation_with_main_turret: true


[attack]

canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

isFixedFiring: true

turretSize: 20
turretTurnSpeed: 3

maxAttackRange: 360
shootDelay: 250

[turret_1]
x: 0
y: 0
canShoot: false
invisible: true

[turret_2]
x: 3
y: 8
attachedTo: 1
slave: true
shoot_sound:cannon_firing
shoot_sound_vol:0.2
recoilOffset: -4


[projectile_1]
directDamage: 150
life: 50
instant: false
trailEffect: true
buildingDamageMultiplier: 0.05
speed: 30
trailEffectRate: 0.2
#deflectionPower: 0.5

[movement]
movementType: LAND
moveSpeed: 0.23
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.9


maxTurnSpeed: 1.0
turnAcceleration: 0.1

moveSlidingMode :true
moveIgnoringBody:false
moveSlidingDir:  181



reverseSpeedPercentage:0


[ai]
upgradedFrom: Isniper


[effect_powerFlash]
priority:low

frameIndex: 0
stripIndex: shockwave

life: 35
fadeOut: true
attachedToUnit: true
color: #FFFFFF
teamColorRatio: 0.8

hSpeed: 0.1
dirSpeed: 2

fadeInTime: 3
scaleFrom: 0.6
scaleTo: 1
alpha: 1
drawUnderUnits:true
liveAfterAttachedDies: true

[attachment_buff]
x:0
y:0

onCreateSpawnUnitOf: powerUp

canBeAttackedAndDamaged: false
keepAliveWhenParentDies: false

setDrawLayerOnBottom: true
rotateWithParent: false
>>>>>>> upstream/REfI
canAttack: false