[core]
#Faction starting structure
#-------------------------------
showInEditor: false
isPickableStartingUnit: true
#-------------------------------
name: 2_gateway_startingUnit
displayText: Faction: BGC
displayText_ru: БГК: Больше-Гривые Кони
copyFrom: gateway.ini
[hiddenAction_created]
autoTriggerOnEvent: created
convertTo: gateway
showQuickWarLogToPlayer: Faction: Galactic mining BGC\n |----------- Gate Way \n |----------- Global Core generated! \n |----------- Produce starting unit: Dark Drone
showQuickWarLogToPlayer_ru: Фракция: Больше-Гривые Кони\n |----------- Связь: Налажена!\n |----------- Капитал: Выдан! \n |----------- Стартовая единица: Негр!
showQuickWarLogToPlayer_zh: 阵营：银河采矿公司 BGC\n |------------门户\n |------------生成全局核心！\n |------------生产起始单位：建造者机甲
#produceUnits: darkdrone_temp
