[core]
copyFrom: ROOT:_BGC_/Drill/drill_T2.ini
showInEditor: true
name: drillT2Off
showActionsWithMixedSelectionIfOtherUnitsHaveTag: fabricator
#overrideAndReplace: fabricatorT2
generation_delay: 0
generation_credits: 0
generation_resources: uranium=0

[action_upgradeT31]
convertTo: decoy_drillT3
price:  0
text: Upgrade
text_ru: Закупка шуриков DeWalt
description_ru: Курс размена будет 5/25
isVisible: if self.tags(includes='decoy')

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
maxAttackRange: 0

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01

maxTurnSpeed: 0
turnAcceleration: 0.1

[graphics]
total_frames: 1

image:        drillOff.png
image_wreak:  NONE
animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 0

[turret_explode]
x:0
y:0
canShoot:false
projectile:explode

[projectile_explode]
life:99
instant: true

speed: 1
largeHitEffect: true
frame: 0
shadowFrame:1
drawType:1

targetGround: true
areaDamage: 450
areaRadius: 90
areaExpandTime:35

deflectionPower:-1

lightColor: #FFEEEE00
lightSize: 1

friendlyFire: true

[ai]
upgradedFrom: drillT1
ai_upgradePriority: 0.7