[core]
#copyFrom: ROOT:data\unitsystem\_Ai_forceRepair_Parent.template
copyFrom: ROOT:data\unitsystem\_shieldguard.template, ROOT:_BGC_/Drill/drill_T1.ini
name: drillT1Off
showActionsWithMixedSelectionIfOtherUnitsHaveTag: fabricator
#price per credit: $1100
generation_delay: 0
generation_credits: 0
generation_resources: uranium=0

footprint: -1,-1,1,1
constructionFootprint: -1,-1,1,1

[action_upgradeT21]
convertTo: decoy_drillT2
text: Upgrade
description: 6:15 uranium-money
text_ru: Закупка шуриков Thakitta
description_ru: - Курс размена будет 6/15
price:  0
isVisible: if self.tags(includes='decoy')


[graphics]
total_frames: 1

image:        drillOff.png
image_wreak:  NONE
animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 0

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
maxAttackRange: 0

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01

maxTurnSpeed: 0
turnAcceleration: 0.1

[turret_explode]
x:0
y:0
canShoot:false
projectile:explode

[projectile_explode]
life:99
instant: true

speed: 1
largeHitEffect: true
frame: 0
shadowFrame:1
drawType:1

targetGround: true
areaDamage: 350
areaRadius: 90
areaExpandTime:35

deflectionPower:-1

lightColor: #FFEEEE00
lightSize: 1

friendlyFire: true

[ai]
buildPriority: 0.40
noneInBaseExtraPriority: 0.25
recommendedInEachBasePriorityIfUnmet: 0.8
noneGlobalExtraPriority: 0.4

ai_upgradePriority: 0.20
maxEachBase: 13
maxGlobal: 40