#head
[core]
dont_load: true
name: type_a_mech_temp
showInEditor: false
copyFrom: type_a_mech.ini


[hiddenAction_MechGantry]
autoTrigger: false
[hiddenAction_onCreate]
autoTriggerOnEvent: created
alsoQueueAction: MechGantryConvertToMainUnit
[hiddenAction_MechGantryConvertToMainUnit]
buildSpeed: ${mechGantryHalttimer}s
convertTo: type_a_mech
[graphics]
showQueueBar: false
[movement]
moveSpeed: 0
maxTurnSpeed: 0