
[core]
#dont_load: true

name: jetpack
displayText: Pegasus
displayDescription: -Advanced armored infantry\n-Light plasma rifles\n-Short-range jetpack
displayText_zh: 珀伽索斯
displayDescription_zh:-高级装甲型步兵\n-武器为轻型等离子步枪\n-能力是使用短程飞行的喷气背包
displayText_ru: Пинус Сильвестрис
displayDescription_ru:- Кальная кислоуродина \n- Не только бегает, но и лётает по приказу \n- Атакует и чернозём, и себе подобных


class: CustomUnitMetadata
price: 1250
maxHp: 325
armour: 1
mass: 3000

techLevel: 2
buildSpeed: 15s
#availableInDemo: true

radius: 7
displayRadius: 9

isBio: true
softCollisionOnAll: 9

selfRegenRate:0.20
isUnrepairableUnit: true

energyMax: 25
energyRegen: 0.02
energyNeedsToRechargeToFull: true

#transportSlotsNeeded: 0.5
tags: infantry

[action_jetpack]
convertTo: EkInfantryJetpackFlying
displayType: upgrade
text: Jetpack
text_zh:喷气背包
text_ru: Реактивный Ранец
pos: 1
description: Allows flight over short gaps
description_ru: - Позволяет кислодировать на короткие расстояния.
description_zh:使用喷气背包将允许进行短距离的飞行
buildSpeed: 0.1s
whenBuilding_cannotMove: true

[hiddenAction_buff]
text: assault mech buff
description: normally unreadable...
autoTrigger: if numberOfUnitsInTeam(withTag="cyborg", withinRange=250, greaterThan=0)
convertTo: jetpackBuff
spawnEffects: CUSTOM:powerFlash

[graphics]
total_frames: 8

image:        jetpack_legs.png
image_wreak:  jetpack_corpse.png
image_turret: jetpack_body.png

image_shadow: infantryshadow_small.png
shadowOffsetX:0.5
shadowOffsetY:0.5

animation_moving_start: 0
animation_moving_end: 7
animation_moving_speed: 6

dustEffect: false

teamColorsOnTurret: true

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 10
turretTurnSpeed: 6

maxAttackRange: 200
shootDelay: 14

aimOffsetSpread: 0.6

[turret_1]
#gun
x: 0
y: 0

#invisible: true
projectile: 1

turnSpeed: 4.0
turnSpeedAcceleration: 1.0

shoot_sound:plasma_fire
shoot_sound_vol:0.3
shoot_light:#33FFCC00

canShoot: true
recoilOffset: 0
#------------------Added 
canAttackLandUnits:   if not self.hasParent(withTag='Helicopter')
invisible:            if self.hasParent(withTag='Helicopter')
[turret_helicopter]
@copyFromSection: turret_1
limitingAngle: 105
canAttackLandUnits:   if self.hasParent(withTag='Helicopter')
invisible:            if not self.hasParent(withTag='Helicopter')
#------------------
[projectile_1]
directDamage: 7
life: 70
speed: 12

frame: 11
color: #DD22FF
drawSize: 0.7

lightColor: #DD22FF
lightSize: 0.5

[effect_powerFlash]
priority:low

frameIndex: 0
stripIndex: shockwave

life: 35
fadeOut: true
attachedToUnit: true
color: #FFFFFF
teamColorRatio: 0.8

hSpeed: 0.1
dirSpeed: 2

fadeInTime: 3
scaleFrom: 0.6
scaleTo: 1
alpha: 1
drawUnderUnits:true
liveAfterAttachedDies: true

[attachment_buff]
x:0
y:0

onCreateSpawnUnitOf: powerUp

canBeAttackedAndDamaged: false
keepAliveWhenParentDies: false

setDrawLayerOnBottom: true
rotateWithParent: false
canAttack: false

[movement]
movementType: LAND
moveSpeed: 0.8
moveAccelerationSpeed: 0.05
moveDecelerationSpeed: 0.12

maxTurnSpeed: 7.5
turnAcceleration: 0.75

targetHeight: 0.01
targetHeightDrift: 0

moveSlidingMode :false
moveIgnoringBody:false
