
[core]
#dont_load: true

name: EkInfantryJetpackFlyingBuff
displayText: Pegasus
displayDescription: -Advanced armored infantry\n-Light plasma rifles\n-Short-range jetpack
displayText_ru: Пинус Сильвестрис [кислый]
displayDescription_ru:- Тот же пинус, но в полёте 
displayText_zh: 珀伽索斯
displayDescription_zh:-高级装甲型步兵\n-武器为轻型等离子步枪\n-能力是使用短程飞行的喷气背包
class: CustomUnitMetadata
price: 1250
maxHp: 375
armour: 5
mass: 3000

techLevel: 2
buildSpeed: 0.0025
showInEditor: false

radius: 7
displayRadius: 9

#builtFrom_1_name: EkInfantryFactoryUpgraded2
#builtFrom_1_pos:  1.85

isBio: true
softCollisionOnAll: 9

energyMax: 25
energyRegen: -0.0001
energyNeedsToRechargeToFull: true

selfRegenRate:0.10
isUnrepairableUnit: true

#transportSlotsNeeded: 0.5
#tags: infantry
[hiddenAction_debuff]
text: assault mech debuff
description: normally unreadable...
autoTrigger: if numberOfUnitsInTeam(withTag="cyborg", withinRange=250, lessThan=1)
convertTo: EkInfantryJetpackFlying
spawnEffects: CUSTOM:powerFlashReverse, CUSTOM:powerFlashReverse2

[action_ForceLand]
convertTo: jetpack
text:Land
text_zh:着陆
text_ru: Упасть
pos: 2
description: Force landing
description_ru: - Быстрый косплей на алкашню.
description_zh: 强制降落
displayType: upgrade
isLocked: if not self.isOverPassableTile(Type='OVER_CLIFF')
buildSpeed: 0.1s
whenBuilding_cannotMove: true

[action_trigger_Land]
convertTo: jetpack
autoTrigger: if self.isEnergyEmpty() and self.isOverPassableTile(Type='OVER_CLIFF')
isVisible: false

[action_trigger_Crash]
addResources: hp=-250
autoTrigger: if self.isEnergyEmpty() and not self.isOverPassableTile(Type='OVER_CLIFF')
isVisible: false

[graphics]

total_frames: 2

image:        jetpack_flying.png
image_wreak:  jetpack_corpse.png

image_shadow: infantryshadow_small.png
shadowOffsetX:0.5
shadowOffsetY:0.5

animation_idle_start: 0
animation_idle_end: 0
animation_idle_speed: 60

animation_moving_start: 1
animation_moving_end: 1
animation_moving_speed: 60

#splastEffect: true
movementEffect: CUSTOM:EkRotorwash, CUSTOM:EkRotordust, CUSTOM:EkJetfire
movementEffectRate: 4

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false

turretSize: 10
turretTurnSpeed: 6

maxAttackRange: 200
shootDelay: 14

aimOffsetSpread: 0.6

[turret_1]
#gun
x: 0
y: 0

#invisible: true
projectile: 1

turnSpeed: 4.0
turnSpeedAcceleration: 1.0

shoot_sound:plasma_fire
shoot_sound_vol:0.3
shoot_light:#33FFCC00

canShoot: true
recoilOffset: 0

[projectile_1]
directDamage: 11
life: 70
speed: 12

frame: 11
color: #DD22FF
drawSize: 0.7

lightColor: #DD22FF
lightSize: 0.5

shieldDamageMultiplier: 2

[effect_EkRotorwash]
image: rotorwash.png
createWhenOverLand: false
delayedStartTimer: 10
life: 20
spawnChance: 1
fadeOut: true
attachedToUnit: false
fadeInTime:2
scaleFrom: 0.1
scaleTo: 1.0
alpha: 0.2
drawUnderUnits:true
hOffset: -20
ySpeedRelative: -0.5
dirOffsetRandom: 180
dirSpeedRandom: 0.6
atmospheric: true

[effect_EkRotordust]
image: rotorwash.png
createWhenOverLiquid: false
delayedStartTimer: 10
life: 20
spawnChance: 1
fadeOut: true
attachedToUnit: false
fadeInTime:2
scaleFrom: 0.1
scaleTo: 1.0
alpha: 0.7
color: #916C5B
drawUnderUnits:true
hOffset: -20
ySpeedRelative: -0.5
dirOffsetRandom: 180
dirSpeedRandom: 0.6
atmospheric: true

[effect_EkJetfire]
image: jetpack_flame.png
life: 15
fadeOut: true
attachedToUnit: false
fadeInTime: 1
scaleFrom: 0.8
scaleTo: 2.2
alpha: 1
xSpeedRelativeRandom: 0.2
ySpeedRelativeRandom: 0.2
yOffsetRelative: -3
ySpeedRelative: 0.5
dirOffsetRandom: 15
drawUnderUnits:true
atmospheric: false

[attachment_buff]
x:0
y:0

onCreateSpawnUnitOf: powerUp

canBeAttackedAndDamaged: false
keepAliveWhenParentDies: false

setDrawLayerOnBottom: true
rotateWithParent: false
canAttack: false

[effect_lightSlowFade]
image: SHARED:light_50.png
life: 20
fadeOut: true
attachedToUnit: true
#color: #63e6e8
color: #FFEECCCC
scaleFrom: 0.2
scaleTo: 0.5
alpha: 0.5
drawUnderUnits:true

[effect_powerFlashReverse]
priority:low

frameIndex: 0
stripIndex: shockwave

life: 55
fadeOut: true
attachedToUnit: true
color: #FFFFFF
teamColorRatio: 0.8

dirSpeed: 2

fadeInTime: 7
scaleFrom: 1
scaleTo: 0.1
alpha: 0.9
drawUnderUnits:true
liveAfterAttachedDies: true

[effect_powerFlashReverse2]
priority:low

image: SHARED:light_50.png

life: 55
fadeOut: true
attachedToUnit: true
color: #FFFFFF
teamColorRatio: 0.8

dirSpeed: 2

fadeInTime: 0
scaleFrom: 0.5
scaleTo: 1
alpha: 1.6
drawUnderUnits:true
liveAfterAttachedDies: true



[effect_projectileLight]
priority:high

image: SHARED:light_50.png
life: 100
fadeOut: true
attachedToUnit: true
color: #FFEECCCC
fadeInTime:2
scaleFrom: 0.3
scaleTo: 0.3
alpha: 0.6
drawUnderUnits:false
liveAfterAttachedDies: false

[movement]
movementType: AIR
moveSpeed: 1.8
moveAccelerationSpeed: 0.02
moveDecelerationSpeed: 0.04

maxTurnSpeed: 7.5
turnAcceleration: 0.75

targetHeight: 20
targetHeightDrift: 0

moveSlidingMode :true
moveIgnoringBody:true

[ai]
upgradedFrom: jetpack
