[core]
name: T2landFactory
displayText: Land Factory T2
displayDescription: aboba aboba aboba 
displayText_ru: Золотой гараж
displayDescription_ru: Сделан из 999-ой пробы \n- Позволяет клепать истинно мощных юнитов внутри себя \n- Инструмент DeWalt в распоряжении
class: CustomUnitMetadata

price: 3000
maxHp: 2000
mass: 9000

radius: 35
#displayRadius: 25
isBio: false
isBuilding: true

techLevel: 2
buildSpeed: 0.0004
overrideAndReplace:T2landFactory
showInEditor: true

exit_x:0
exit_y:-1
exit_moveAwayAmount:120

footprint: -1,-1,1,1

constructionFootprint: -1,-1,1,2

canBuild_1_name: setRally
canBuild_1_pos:  0.1

[canBuild_Tab1]
pos: 1
name: builder,scout,c_tank,c_hovertank,c_artillery,saberTank,Typhoon,cometTank
isVisible: if not self.isControlledByAI()
[canBuild_Tab2]
pos: 2
name: c_heavyTank,plasmaTankA,c_heavyHovertank,zephyrTank,cc_laserTank,buffalo,Radar Truck,missileTank,

[canBuild_Tab3]
pos: 3
name: demo_truck,dusterTank,heavyArtillery,Tesla Tank,achillesTank,behemothTank,combatEngineerX

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
maxAttackRange: 0


[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01

maxTurnSpeed: 0
turnAcceleration: 0.1

[animation_openDoor]
onActions: queuedUnits
onActionsQueuedUnitPlayAt: 0.8
blendIn: 2s 
blendOut: 2s 
arm1_0: {x:0, y:20}

[graphics]
image:       LFFT2.png
image_back:  LFB.png
image_wreak:  LFD.png

[arm_1]
x:0
y:0
image_end:LandFactDoor.png
drawOverBody:true

[arm_2]
x:0
y:0
image_end:LFFT2.png
drawOverBody:true
image_end_teamColors:true

[ai]

#upgradedFrom: landFactory
maxEachBase:0
maxGlobal:0
upgradedFrom: landFactorya

[action_upgrade]
isVisible:false 