
[core]

copyFrom: _weapun(SF).template, _SFmainGun.template, ROOT:data\effects\muzzle_flash_blueLarge.template, ROOT:data\effects\muzzle_smoke.template, ROOT:data\effects\DropBomb.ini, ROOT:data\effects\water_byHawko.template,ROOT:statusEffect.template
name: LandkreuzerSF
displayText: Landkreuzer
displayDescription: "Who bathes in worldly joy, swims in world of fears"\n- Heavy Armored Multi-Purpose Land Cruiser\n- Has Backup system and repairs transported unit \n- Armed with dual Rail Guns and built-in Fabricator\n- Long range and capable of piercing multiple units\n- Can attack surface and air units\n- Can only have ${landcruiser_Limit} built at a time.\n--------------------------\nWeapon: [2x Rail Gun], Target: Land\nAccuracy: Good, Burst size: 2, \nSecWeapon: [2x Twin Missile Pod], [1x Auto cannon], [SAM], [2x Flak]
displayText_ru: Сухопупный Рейсер
displayDescription_ru: Версия Тойоты, подогнанная под разнос врага \n- Имеет куда более лучшие показатели для бытия полезным на поле боя \n- Радиус залпования больше, урон выше, ход и разгон быстрее \n- В качестве справедливого размена обрезается в крафте кислых юнитов \n- Всё ещё может создавать некоторую мелочь себе в допомогу \n- Также перестаёт генерировать деньги и переносить внутри себя юнитов \n- Он потребует к себе внимания, ведь резервное восстановление отключено, а взрыв только усилен \n- Серьёзный ответ врагу, но с небольшим нюансом
displayText_zh: 兰德·克鲁兹
displayDescription_zh:“沐浴在世俗的欢乐中，游荡在恐惧的世界里”\n-重型装甲多用途陆地巡洋舰\n-被摧毁后启动备用系统，能够维修被运输的部队\n-配备双管轨道炮和内置资源制造仪\n-主炮远程攻击并能够穿透多个敌人\n-可以攻击非水下单位和空中部队\n-最大同时存在数量：${landcruiser_Limit}\n---------------------------------------\n武器：[双管轨道炮]，攻击目标：陆地单位\n精度：良好，\n副武器：[2x双弹导弹发射器]，[1x自动火炮]，[萨姆]，[2x高射炮]
class: CustomUnitMetadata

price: landcruiser=1
maxHp: 22000
mass: 900000
armour: 25

techLevel: 1
experimental: true

buildSpeed: 0.0002
#buildSpeed: 1

#availableInDemo: true

radius: 60
displayRadius: 60

fogOfWarSightRange: 30
transportSlotsNeeded: 999

isBio: false
isBuilder: true
softCollisionOnAll: 3

exit_moveAwayAmount:70
exit_x: 0
exit_y: 110

selfRegenRate: 0.4
#builtFrom_1_name: commandCenter
#builtFrom_1_pos:  2

#builtFrom_1_name: experimentalLandFactory
#builtFrom_1_pos:  6

#energyMax: 2
#energyRegen: 0.0003

energyMax: 2
energyRegen: -0.05


nukeOnDeath: true
nukeOnDeathRange: 300
nukeOnDeathDamage: 6500
nukeOnDeathDisableWhenNoNuke: true
borrowResourcesWhileAlive: landcruiser=1

autoTriggerCooldownTime: 0.01s
autoTriggerCooldownTime_allowDangerousHighCPU: true

disableDeathOnZeroHp: false
tags: landCrues, exp, carrierS, 50k, idontlikestuns
soundOnNewSelection:toyota.ogg

[hiddenAction_cringeHp]
autoTrigger: if self.hasFlag(id=8)
addResources: hp=-13000, unsetFlag=8, setFlag=9

[action_techUp]
displayType: upgrade
price:  50000, uranium=3000
text: Upgrade - T3
description: Improve my desire|
text_zh: 改造 - Tech-3
description_zh: 改善我的欲望
text_ru: Рекомбинация
description_ru: Ожирение спадает \n- Характеристики движения и орудий значительно снижаются \n- Возможность второй жизни возвращается, мощность пука снижается \n- Восстанавливается возможность создания некоторых юнитов и их переноса
buildSpeed: 200s
#whenBuilding_cannotMove:true
allowMultipleInQueue: false
pos: 0.1
convertTo: Landkreuzer
isLockedAlt: if self.queueSize(greaterThan=0)
spawnUnits: Landkreuzer
deleteSelf: true

[canBuild_units]
name: darkdrone, basicII, RepairMech, ion_Mech, aarocket_Mech, Mist, modularMech
pos: 1

#----------------------------------------------------------------
[hiddenAction_death]
spawnEffects: CUSTOM:deathBody
[graphics]
drawLayer: experimentals
total_frames: 1

image:        sample4.png
image_wreak:  NONE
image_turret: NONE
#scaleImagesTo: 20
#scaleTurretImagesTo: 9

teamColorsOnTurret: true

image_shadow: AUTO
shadowOffsetX:3
shadowOffsetY:3

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 30
turretTurnSpeed: 2.2
maxAttackRange: 425
shootDelay: 60

turretMultiTargeting: true

[turret_Dummy_A]
#dummy and hull
x: 0
y: 0
projectile: Dummy
size: 5
image: hull.png
shoot_sound:NONE
shoot_sound_vol:0
shoot_flame: NONE
canShoot: true
turnSpeed: 100
turnSpeedAcceleration: 100
canAttackFlyingUnits: false
canAttackLandUnits:   false
limitingRange: ${SFmainLimitRng}
showRangeUIGuide: true
[turret_Dummy_B]
#dummy RAIL GUN over penetration
x: 0
y: 0
projectile: Dummy
size: 5
invisible: true
shoot_sound:NONE
shoot_sound_vol:0
shoot_flame: NONE
canShoot: true
turnSpeed: 100
turnSpeedAcceleration: 100
canAttackFlyingUnits: false
canAttackLandUnits:   false
limitingRange: 850
showRangeUIGuide: true
#========================Secondary II
[turret_SecondaryIIkannon_A]
#cannon
x: 0
y: -5
attachedTo: SecondaryII_A
slave: true
invisible: false

image:t_cannonbarrel.png

delay: ${SFsecondaryDelayII}s

projectile: SecII

turnSpeed: 100
turnSpeedAcceleration: 100

shoot_sound:ROOT:data\soundFx\weapon_heavyGun_2.ogg
shoot_sound_vol:0.15
shoot_flame:CUSTOM:muzzleFlame
shoot_light:#FFccCCEE
limitingRange: ${SFsecondaryRangeII}
recoilOffset: 0
recoilOutTime: 1
recoilReturnTime: 10

canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
canShoot: true

size: 30
[turret_SecondaryII_A]
x: 11
y: 31
limitingAngle: 80
turnSpeed: 2
turnSpeedAcceleration: 0.5
image: velarus_cannon.png
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false
canShoot: false

recoilOffset: 0
recoilOutTime: 1
recoilReturnTime: 10
limitingRange: ${SFsecondaryRangeII}
#========================
idleSweepAddRandomAngle:5
idleSweepAngle:15
idleSweepDelay:600
idleSweepAddRandomDelay: 800
idleSweepSpeed:0.3
#===================================================
[turret_Dummy_ATop]
@copyFromSection: turret_Dummy_A
image: hull_top.png

[turret_SAM_a]
#
x: 32
y: -66

idleDir:0
turnSpeed: 0
canAttackMaxAngle: 181
invisible: true
image: ROOT:data\dotGuide.png
size: 0

canAttackFlyingUnits: true
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
limitingRange: ${SFsecondaryRange}
projectile: mmm
shoot_sound:missile_fire
shoot_sound_vol:0.2
shoot_flame: CUSTOM:backblast*2
shoot_light:#82e580
delay: 160
[turret_SAM_b]
@copyFromSection: turret_SAM_a
y: -69
linkDelayWithTurret: SAM_a
warmup:30
[turret_SAM_c]
@copyFromSection: turret_SAM_a
y: -72
linkDelayWithTurret: SAM_a
warmup:60
#-------------
[turret_SAM_d]
@copyFromSection: turret_SAM_a
x: -32
y: -66
idleDir:0
#linkDelayWithTurret: SAM_a
warmup:0
[turret_SAM_e]
@copyFromSection: turret_SAM_d
y: -69
linkDelayWithTurret: SAM_d
warmup:30
[turret_SAM_f]
@copyFromSection: turret_SAM_d
y: -72
linkDelayWithTurret: SAM_d
warmup:60
#================================================ rocket mortar
[turret_RP_A1]
#invisible: true
x: 32
y: -74
idleDir:0
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: true
#canAttackNotTouchingWaterUnits: false

shoot_sound:ROOT:data\soundFx\weapon_micromissiles.ogg
shoot_sound_vol:1
shoot_light:#FFEECCCC

image: ROOT:data\dotGuide.png
projectile: RPod
size: 0
#turnSpeed: 15
delay: 6.5s
turnSpeed: 0
canAttackMaxAngle: 181
warmup: 0
[turret_RP_A2]
@copyFromSection: turret_RP_A1
x: 28
linkDelayWithTurret: RP_A1
warmup:10
[turret_RP_A3]
@copyFromSection: turret_RP_A1
y: -78
linkDelayWithTurret: RP_A1
warmup:20
[turret_RP_A4]
@copyFromSection: turret_RP_A1
x: 28
y: -78
linkDelayWithTurret: RP_A1
warmup:30
[turret_RP_A5]
@copyFromSection: turret_RP_A1
linkDelayWithTurret: RP_A1
y: -82
warmup:40
[turret_RP_A6]
@copyFromSection: turret_RP_A1
x: 28
y: -82
linkDelayWithTurret: RP_A1
warmup:50
#----------------
[turret_RP_B1]
@copyFromSection: turret_RP_A1
x: -32
y: -74
[turret_RP_B2]
@copyFromSection: turret_RP_B1
x: -28
linkDelayWithTurret: RP_B1
warmup:10
[turret_RP_B3]
@copyFromSection: turret_RP_B1
y: -78
linkDelayWithTurret: RP_B1
warmup:20
[turret_RP_B4]
@copyFromSection: turret_RP_B1
x: -28
y: -78
linkDelayWithTurret: RP_B1
warmup:30
[turret_RP_B5]
@copyFromSection: turret_RP_B1
linkDelayWithTurret: RP_B1
y: -82
warmup:40
[turret_RP_B6]
@copyFromSection: turret_RP_B1
linkDelayWithTurret: RP_B1
warmup:50
y: -82
#==================================
[projectile_RPod]
#torpedo
directDamage: 5
areaDamage: 20
areaRadius: 80

life: 2
speed: 1
targetSpeed: 2
targetSpeedAcceleration: 0.05

drawSize: 0.8
image: canister.png

color: #1E1E96
largeHitEffect: true

deflectionPower: -1

wobbleAmplitude: 0.1
wobbleFrequency: 0.8s

ballistic: true
ballistic_delaymove_height:90
ballistic_height: 80

buildingDamageMultiplier: 10

turnSpeed:0

#startingTurnSpeed:1
#targetTurnSpeed:3

lightSize:1
lightColor: #37f9e1

#spawnProjectilesOnEndOfLife: torpedo_split(offsetDir=90), torpedo_split(offsetDir=-90), torpedo_split(offsetDir=00)
spawnProjectilesOnEndOfLife: RPodLocked
effectOnCreate: CUSTOM:backblast_RP*3
trailEffect: CUSTOM:smokeW
trailEffectRate: 2
spawnUnit: BGCflameSpawner
[projectile_RPodLocked]
@copyFromSection: projectile_RPod
life: 30
turnSpeed:0.5
spawnProjectilesOnEndOfLife: RPodLocked2
ballistic: false

gravity:98
initialUnguidedSpeedHeight: 100
effectOnCreate: NONE
[projectile_RPodLocked2]
@copyFromSection: projectile_RPodLocked
life: 50
turnSpeed:3
speed: 3
targetSpeed: 3
targetSpeedAcceleration: 0.05
spawnProjectilesOnEndOfLife: RPodLocked3

gravity:4
initialUnguidedSpeedHeight: 5

targetGround: true
targetGroundSpread: 55

autoTargetingOnDeadTarget: false
effectOnCreate: NONE
[projectile_RPodLocked3]
@copyFromSection: projectile_RPodLocked2
life: 300
turnSpeed:4
speed: 5
spawnProjectilesOnEndOfLife: NONE
explodeOnEndOfLife: true
effectOnCreate: NONE

explodeEffect: CUSTOM:projectileWaterDust, CUSTOM:projectileWaterSplash*5,CUSTOM:muzzlescorchmark, CUSTOM:Boom, CUSTOM:FlakBoom2, CUSTOM:FLight, CUSTOM:smokeW*3
explodeEffectOnShield: CUSTOM:projectileWaterDust, CUSTOM:projectileWaterSplash*5,CUSTOM:muzzlescorchmark, CUSTOM:Boom, CUSTOM:FlakBoom2, CUSTOM:FLight, CUSTOM:smokeW*3
[projectile_Dummy]
#dummy
directDamage: 0
life: 0
speed: 0
drawSize: 0
color: #46ebff
lightColor: #46ebff
lightSize: 0

[projectile_SecII]
directDamage: ${SFsecondarynDmgII*1.5}
life: 70
speed: 10

frame: 2
trailEffect: true
trailEffectRate: 2
largeHitEffect: true

image: ROOT:data\images\projectile2.png
drawSize: 1

effectOnCreate: CUSTOM:smoke*3
[projectile_mmm]
areaDamage: 30
areaRadius: 55
life: 50
speed: 2
targetSpeed: 4
turnSpeed:3


color: #fff7ff1d

drawSize: 1.9

trailEffect: true
largeHitEffect: true

lightColor: #f7ff1d
lightSize: 0.5

effectOnCreate: CUSTOM:backblast_not*5
spawnProjectilesOnEndOfLife: mmm_A
[projectile_mmm_A]
@copyFromSection: projectile_mmm
life: 250
areaDamage: 50
speed: 4
turnSpeed:4
spawnProjectilesOnEndOfLife: NONE

#=====================--
autoTargetingOnDeadTargetRange: 500
autoTargetingOnDeadTargetLead: 500
retargetingInFlight: true
#=======================
[leg_1]
x: -35
y: 35
attach_x: -20
attach_y: 20
moveSpeed: 2
moveWarmUp:0.05s

rotateSpeed: 7
hidden: if self.hasFlag(id=3)
heightSpeed: 0.5
resetAngle:25

image_leg:  leg_f.png
image_foot: foot.png
image_foot_shadow: SHADOW:foot.png
#draw_foot_on_top: true
#dust_effect: false

holdDisMin: 20
holdDisMax: 30

hardLimit: 40

endDirOffset:45

[leg_2]
@copyFromSection: leg_1
x: 35
y: 35
attach_x: 20
attach_y: 20

endDirOffset:-45

[leg_3]
@copyFromSection: leg_1
x: -45
y: -55
attach_x: -20
attach_y: -25

image_leg:  leg_b.png
endDirOffset:-45

[leg_4]
@copyFromSection: leg_1
x: 45
y: -55
attach_x: 20
attach_y: -25

image_leg:  leg_b.png
endDirOffset:45
[effect_deathBody]
image: hull_w.png
imageShadow: hull_w.png
priority: high

attachedToUnit: false
life: 2500
physics: false
shadow: true

dirOffset: 0
alpha: 3
drawUnderUnits: true
[movement]
movementType: OVER_CLIFF_WATER
moveSpeed: 0.45
moveAccelerationSpeed: 0.0055
moveDecelerationSpeed: 0.085

targetHeight: 0
targetHeightDrift: 0

reverseSpeedPercentage:0.95

maxTurnSpeed: 0.39
turnAcceleration: 0.2

moveSlidingMode :true
moveIgnoringBody:true
moveSlidingDir:  45


slowDeathFall: true


[ai] 
useAsBuilder: true
useAsTransport: false







