
[core]

copyFrom: mirv.ini

showInEditor: true
isLockedIfGameModeNoNuke:true

name: EkMirvSpawner
class: CustomUnitMetadata

tags: H-end, mirv

[hiddenAction_disrupted]
autoTriggerOnEvent: newMessage(withTag="disruption_MIRV")
deleteSelf: true
showMessageToAllEnemyPlayers: %{self.playerName}s laser has been successfully disrupted!
showMessageToAllEnemyPlayers_ru: Личинус %{self.playerName} успешно улетел обратно!
playSoundGlobally: ROOT:data/soundFx/_quick_poop.ogg:5

[action_triggerSpawn]
autoTrigger: if self.energy(greaterThan=0)
isVisible: false
convertTo: EkMirv

[graphics]
total_frames: 1

#image:        icon_mirv.png
image: SHARED:icon_attack_point.png
image_wreak:  NONE
image_turret: NONE

#scaleImagesTo: 20
#scaleTurretImagesTo: 9

image_shadow: NONE