<<<<<<< HEAD
[core]
@global tech: 3

name: Pop_turretT3

displayText: Pop Turret T3
displayText_ru: Опрыскиватель 
displayDescription_ru: - Поливает врагов не самым приятном шквалом пуль \n- Отлично забетонирован \n- Скорострельность ещё больше, и урон, однако, выше
displayDescription_zh:-只能攻击地面单位\n-打爆地面单位！
showInEditor: true
class: CustomUnitMetadata
maxHp: 5000
mass: 9000
armour:9
price: 12500

techLevel: 2
buildSpeed: 75s
fogOfWarSightRange: 18
copyFrom:Pop_turret.ini


[action_upgrade_T2]
@copyFrom_skipThisSection:true
[action_upgrade_rockTurret]
@copyFrom_skipThisSection:true
[action_upgrade_acid_turret]
@copyFrom_skipThisSection:true
[action_upgrade_laser_turret]
@copyFrom_skipThisSection:true
[action_upgrade_RM_turret]
@copyFrom_skipThisSection:true
[attack]

maxAttackRange: 320
shootDelay: 1.1s

[ai]
upgradedFrom: Pop_turret

[projectile_1]
#Machingun
directDamage: 0
life: 9999
speed: 9
drawSize: 0.6

largeHitEffect: true
frame: 2
targetGround: true
targetGroundSpread: 30
areaDamage: 40
areaRadius: 60
trailEffect: false

explodeEffect:CUSTOM:silent

hullDamageMultiplier: 1.3
buildingDamageMultiplier: 2
shieldDamageMultiplier: 2
lightColor: #ffe92b
=======
[core]
@global tech: 3

name: Pop_turretT3

displayText: Pop Turret T3
displayText_ru: Опрыскиватель 
displayDescription_ru: - Поливает врагов не самым приятном шквалом пуль \n- Отлично забетонирован \n- Скорострельность ещё больше, и урон, однако, выше
displayDescription_zh:-只能攻击地面单位\n-打爆地面单位！
showInEditor: true
class: CustomUnitMetadata
maxHp: 5000
mass: 9000
armour:9
price: 12500

techLevel: 2
buildSpeed: 75s
fogOfWarSightRange: 18
copyFrom:Pop_turret.ini


[action_upgrade_T2]
@copyFrom_skipThisSection:true
[action_upgrade_rockTurret]
@copyFrom_skipThisSection:true
[action_upgrade_acid_turret]
@copyFrom_skipThisSection:true
[action_upgrade_laser_turret]
@copyFrom_skipThisSection:true
[action_upgrade_RM_turret]
@copyFrom_skipThisSection:true
[attack]

maxAttackRange: 320
shootDelay: 1.1s

[ai]
upgradedFrom: Pop_turret

[projectile_1]
#Machingun
directDamage: 0
life: 9999
speed: 9
drawSize: 0.6

largeHitEffect: true
frame: 2
targetGround: true
targetGroundSpread: 30
areaDamage: 40
areaRadius: 60
trailEffect: false

explodeEffect:CUSTOM:silent

hullDamageMultiplier: 1.3
buildingDamageMultiplier: 2
shieldDamageMultiplier: 2
lightColor: #ffe92b
>>>>>>> upstream/REfI
lightSize: 0.01