
[core]
name: modularSpiedr_shieldGen
copyFrom: common_slot.ini

displayText: Shield Generator Module
displayText_ru: 5G Генератор
displayDescription: - Shield generation module, obviously \n- Gives extra amount of shields to unit without increasing pool of hitpoints. \n- Still shitty, compared to BGC ones
displayDescription_ru: Первокласснейший генератор 5G для паукана \n- Ускоряет регенерацию 5G щитов, но не увеличивает его пул \n- Реген довольно неплох на уровне для ауешника, \n - Хоть и не идет ни в какое сравнение с модулями БГК

price: 6000


[hiddenAction_regen]
autoTrigger: true

#30 / 60 = 0.5 per tick
takeResources: shield=-60
takeResources_includeParent: true
takeResources_discardCollected: true


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 30
turretTurnSpeed: 2
#maxAttackRange: 200
shootDelay: 85


[graphics]

image:        shieldGen.png


image_shadow: NONE
shadowOffsetX:3
shadowOffsetY:3

drawLayer: bottom



