
[core]
name: modularSpiedr_speed
copyFrom: common_slot.ini

displayText: Speed Module
displayText_ru: Спиды
displayDescription: - Mobility Module for Spider \n - You can find it useless, but it's actually the best thing for this big unit. \n - Nullifies all speed debuffs from modules \n - No sense in placing more than one module
displayDescription_ru: Необычный модуль \n- Позволяет вывести эту мамашу на сверхзвук \n- Но больше одного ставить смысла нет

price: 6000
tags: ${baseTags}, modularSpiedr_speedSlot


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   true
canAttackUnderwaterUnits: false

turretSize: 30
turretTurnSpeed: 2
#maxAttackRange: 200
shootDelay: 85


[graphics]

image:        speed.png


image_shadow: NONE
shadowOffsetX:3
shadowOffsetY:3

drawLayer: bottom



