<<<<<<< HEAD
[core]
@global cons: 6
showInEditor: true
name: drillT2
mass: 9000
radius: 20

displayText: Drill T-II
displayText_ru: Дрель-шуруповёрт Thakitta
displayText_zh: 钻井 Tech-II
displayDescription: loh
displayDescription_ru: Более выговный размен ресурсов: 6/15 \n- При недостатке Терпение дрель автоматически затормаживается
price: 4500
maxHp: 1000
#overrideAndReplace: fabricatorT2
generation_delay: 40
generation_credits: 15
generation_resources: uranium=-${cons}
techLevel: 2
buildSpeed: 0.0004

footprint: -1,-1,1,1
constructionFootprint: -1,-1,1,1

isBuilding: true
#overrideAndReplace: fabricator
fireTurretXAtSelfOnDeath: explode

[hiddenAction_GetUp]
autoTrigger: if self.resource(type="uranium") >= 4*${cons} and not self.tags(includes='decoy')
convertTo: drillT2
[hiddenAction_GetUpDecoy]
autoTrigger: if self.resource(type="uranium") >= 4*${cons} and self.tags(includes='decoy')
convertTo: decoy_drillT2

[hiddenAction_GetDown]
autoTrigger: if self.resource(type="uranium") < 4*${cons}
convertTo_keepCurrentTags: true
convertTo: drillT2Off

[action_upgradeT2]
@copyFrom_skipThisSection:true

[action_upgradeT3]
isVisible: if not self.tags(includes='decoy')
convertTo: drillT3
price:  5000
text: Upgrade
text_ru: Закупка шуриков DeWalt
description_ru: Курс размена будет 5/25
text_zh: 技术升级
#description: i:units.fabricator.upgrade.descriptionT3
displayType: upgrade
buildSpeed: 55.6s

iconExtraImage: SHARED:icon_upgrade_top.png
iconExtraColor: #AAFFFFFF

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
maxAttackRange: 0

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01

maxTurnSpeed: 0
turnAcceleration: 0.1

[graphics]
total_frames: 4

image:        drillT2.png
image_wreak:  NONE
animation_idle_start: 1
animation_idle_end: 3
animation_idle_speed: 9

[turret_explode]
x:0
y:0
canShoot:false
projectile:explode

[projectile_explode]
life:99
instant: true

speed: 1
largeHitEffect: true
frame: 0
shadowFrame:1
drawType:1

targetGround: true
areaDamage: 450
areaRadius: 90
areaExpandTime:35

deflectionPower:-1

lightColor: #FFEEEE00
lightSize: 1

friendlyFire: true

[ai]
upgradedFrom: drillT1
=======
[core]
@global cons: 6
showInEditor: true
name: drillT2
mass: 9000
radius: 20

displayText: Drill T-II
displayText_ru: Дрель-шуруповёрт Thakitta
displayText_zh: 钻井 Tech-II
displayDescription: loh
displayDescription_ru: Более выговный размен ресурсов: 6/15 \n- При недостатке Терпение дрель автоматически затормаживается
price: 4500
maxHp: 1000
#overrideAndReplace: fabricatorT2
generation_delay: 40
generation_credits: 15
generation_resources: uranium=-${cons}
techLevel: 2
buildSpeed: 0.0004

footprint: -1,-1,1,1
constructionFootprint: -1,-1,1,1

isBuilding: true
#overrideAndReplace: fabricator
fireTurretXAtSelfOnDeath: explode

[hiddenAction_GetUp]
autoTrigger: if self.resource(type="uranium") >= 4*${cons} and not self.tags(includes='decoy')
convertTo: drillT2
[hiddenAction_GetUpDecoy]
autoTrigger: if self.resource(type="uranium") >= 4*${cons} and self.tags(includes='decoy')
convertTo: decoy_drillT2

[hiddenAction_GetDown]
autoTrigger: if self.resource(type="uranium") < 4*${cons}
convertTo_keepCurrentTags: true
convertTo: drillT2Off

[action_upgradeT2]
@copyFrom_skipThisSection:true

[action_upgradeT3]
isVisible: if not self.tags(includes='decoy')
convertTo: drillT3
price:  5000
text: Upgrade
text_ru: Закупка шуриков DeWalt
description_ru: Курс размена будет 5/25
text_zh: 技术升级
#description: i:units.fabricator.upgrade.descriptionT3
displayType: upgrade
buildSpeed: 55.6s

iconExtraImage: SHARED:icon_upgrade_top.png
iconExtraColor: #AAFFFFFF

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:   false
canAttackUnderwaterUnits: false
maxAttackRange: 0

[movement]
movementType: NONE
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01

maxTurnSpeed: 0
turnAcceleration: 0.1

[graphics]
total_frames: 4

image:        drillT2.png
image_wreak:  NONE
animation_idle_start: 1
animation_idle_end: 3
animation_idle_speed: 9

[turret_explode]
x:0
y:0
canShoot:false
projectile:explode

[projectile_explode]
life:99
instant: true

speed: 1
largeHitEffect: true
frame: 0
shadowFrame:1
drawType:1

targetGround: true
areaDamage: 450
areaRadius: 90
areaExpandTime:35

deflectionPower:-1

lightColor: #FFEEEE00
lightSize: 1

friendlyFire: true

[ai]
upgradedFrom: drillT1
>>>>>>> upstream/REfI
ai_upgradePriority: 0.7